### ISSUE TITLE
Xorg Segfault

### ISSUE THREAD

**Issue by AustinJ235** [Ashark/archlinux-amdgpu#34]
My issue with the libc segfault during xorg startup still exists on a fresh install of Antergos. Xorg has been downgraded to 1.18.4. Also the dkms fails to build on this install for some reason, maybe a new kernel?

EDIT: This is on a RX 480

**xorg log** https://austinj.me/logs/fresh/1/xorg.txt
**make log** https://austinj.me/logs/fresh/1/make.txt

**Comment by corngood** [comment]
I'd focus on the dkms error for now.  It's very strange... I've built it against 4.9.8 myself.  It's almost like some of the patches aren't being applied.  I'll investigate mine a bit more.

**Comment by corngood** [comment]
Seems like #35 represents the same dkms compilation error.  Let's discuss that problem there, and leave this issue for the xorg crash.

**Comment by AustinJ235** [comment]
My issue may be related to this known issue on the driver, "System fails to boot to OS with DP1.2 enabled on RHEL 7.3." I have had time to test out the driver on stock ubuntu or rhel to make sure this isn't a packaging issue.

**Comment by corngood** [comment]
I really wouldn't worry too much about the xorg crash until you can get the dkms module compiling.  It's not going to work properly without it.  From your xorg log:
```
[    17.727] (II) AMDGPU(0): AMDGPU DDX hybrid version: 16.60.3
[    17.727] (EE) AMDGPU(0): Failed to open amdgpu hybrid version
```
That shows you that it's not using the correct kernel module.

**Comment by AustinJ235** [comment]
Same issue still occurs after fixing the dkms install issue. Doesn't seem to be the known issue from RHEL with display port 1.2 as I switched to hdmi only and get the same segfault. HDMI is outputing wonky text to the console for some reason.

https://austinj.me/logs/fresh/3/xorg.txt

https://austinj.me/logs/fresh/3/IMG_20170213_174232.jpg
_Sorry for the blurry image, my phone didn't want to focus on the text._
