### ISSUE TITLE
Kernel module doesn't build on linux-4.10

### ISSUE THREAD

**Issue by corngood** [Ashark/archlinux-amdgpu#36]
I had a look at 4.10-rc7 today.  Here's the patch I've come up with so far:

https://github.com/corngood/nixpkgs/blob/amdgpu-pro/pkgs/os-specific/linux/amdgpu-pro/patches/0005-fixes-for-linux-4.10.patch#L2694

I didn't bother wrapping anything with version guards.  Since it's so big I was just going to apply it conditionally.  Looks like similar work was done for Gentoo, and it was wrapped properly:

https://github.com/Lucretia/vulkan-overlay/commit/d5288d1ba8021f19cafef5c2acab817f486ea263

My machine locks up around when the driver is loaded (or possibly tty mode switch).  I haven't done much investigation, but I thought I'd leave the patch here in case anyone wants to try it out.

@brainpower

**Comment by Gelmo** [comment]
Yesterday I tried building on 4.10 w/ Ck/BFS, no luck. Unfortunately I accidentally deleted the make.log. Let me know if you have any specific steps that you want tested; I should have some free time this week.

**Comment by yshui** [comment]
I experimented a bit. Looks like you don't need amdgpu-pro's kernel module anymore. 4.10's amdgpu works just fine with amdgpu-pro userspace.
