### ISSUE TITLE
No Package : 'libdrm' Found 

### ISSUE THREAD

**Issue by xiconxi** [Ashark/archlinux-amdgpu#38]
I'm new to archlinux
I had upgraded libdrm to amdgpu-pro-libdrm. And I uninstall the Package xorg-server1.19 to downgrade to 1.18. then I get  this error.
I tried to fix it , I founded some info in the warning in [PKGBUILD-Wiki](https://wiki.archlinux.org/index.php/PKGBUILD#provides)
Change provides=('lib32-libdrm') to provides=('lib32-libdrm-2.4.11-2')
But it didn't work out.

**Comment by brainpower** [comment]
`provides=('lib32-libdrm-2.4.11-2')` is wrong. It should be `provides=('lib32-libdrm=2.4.11-2')`. With an `=` sign not a minus between package name and version.
But if 'libdrm' is not found, shouldn't you change the `provides=('libdrm')` instead of the lib32 one?
