### ISSUE TITLE
Xorg Crash with AMDGPU-Pro install

### ISSUE THREAD

**Issue by StripedMonkey** [Ashark/archlinux-amdgpu#40]
http://pastebin.com/aPJ3jyGK
I sucessfully tested that I got into Xorg 1.18 without issue before installing amdgpu-pro, journalctl shows a core dump that I can post if you would like. I'm a bit of a noob when it comes to graphics so please point out anything that I'm missing.

**Comment by Gelmo** [comment]
```$ cat temppppp | grep -v 'REEMP\|(WW)' | grep EE
[  1356.234] (EE) Failed to load module "glx" (module does not exist, 0)
[  1356.234] (EE) Failed to load module "ati" (module does not exist, 0)
[  1356.235] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1356.235] (EE) Failed to load module "vesa" (module does not exist, 0)
[  1356.286] (EE) 
[  1356.286] (EE) Backtrace:
[  1356.286] (EE) 0: /usr/lib/xorg-server/Xorg (OsLookupColor+0x139) [0x59c859]
[  1356.287] (EE) 1: /usr/lib/libc.so.6 (__restore_rt+0x0) [0x7f8abb6130af]
[  1356.287] (EE) 2: /usr/lib/libdrm_amdgpu.so.1 (amdgpu_get_marketing_name+0x0) [0x7f8ab30ecad0]
[  1356.287] (EE) 3: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (getIcdInterfaceGL+0x2438) [0x7f8ab72f6578]
[  1356.287] (EE) 4: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (getIcdInterfaceGL+0x2a91) [0x7f8ab72f7231]
[  1356.288] (EE) 5: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (getIcdInterfaceGL+0x5a5a) [0x7f8ab72fcfea]
[  1356.288] (EE) unw_get_proc_name failed: no unwind info found [-10]
[  1356.288] (EE) 6: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (?+0x5a5a) [0x7f8ab677a39a]
[  1356.288] (EE) unw_get_proc_name failed: no unwind info found [-10]
[  1356.288] (EE) 7: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (?+0x5a5a) [0x7f8ab6722afa]
[  1356.288] (EE) unw_get_proc_name failed: no unwind info found [-10]
[  1356.288] (EE) 8: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (?+0x5a5a) [0x7f8ab54b17ea]
[  1356.289] (EE) unw_get_proc_name failed: no unwind info found [-10]
[  1356.289] (EE) 9: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (?+0x5a5a) [0x7f8ab6392fba]
[  1356.289] (EE) 10: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (getIcdInterfaceGL+0xf40) [0x7f8ab72f3bb0]
[  1356.289] (EE) 11: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (eglCreateContext+0x7528) [0x7f8ab7261d78]
[  1356.289] (EE) 12: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (eglCreateContext+0x7886) [0x7f8ab7262436]
[  1356.290] (EE) 13: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (eglCreateContext+0x1f78) [0x7f8ab7257288]
[  1356.290] (EE) 14: /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so (eglInitialize+0xbf) [0x7f8ab72529bf]
[  1356.290] (EE) 15: /usr/lib/xorg/modules/libglamoregl.so (glamor_egl_init+0xe5) [0x7f8ab8d78125]
[  1356.290] (EE) 16: /usr/lib/xorg/modules/drivers/modesetting_drv.so (_init+0x3b06) [0x7f8ab8fb37b6]
[  1356.291] (EE) 17: /usr/lib/xorg-server/Xorg (InitOutput+0xac5) [0x47cd85]
[  1356.291] (EE) 18: /usr/lib/xorg-server/Xorg (remove_fs_handlers+0x266) [0x43a516]
[  1356.291] (EE) 19: /usr/lib/libc.so.6 (__libc_start_main+0xf1) [0x7f8abb600291]
[  1356.291] (EE) 20: /usr/lib/xorg-server/Xorg (_start+0x29) [0x424609]
[  1356.292] (EE) 21: ? (?+0x29) [0x29]
[  1356.292] (EE) 
[  1356.292] (EE) Segmentation fault at address 0x110
[  1356.292] (EE) 
[  1356.292] (EE) Caught signal 11 (Segmentation fault). Server aborting
[  1356.292] (EE) 
[  1356.292] (EE) 
[  1356.292] (EE) Please also check the log file at "/home/monkey/.local/share/xorg/Xorg.0.log" for additional information.
[  1356.292] (EE) 
[  1356.296] (EE) Server terminated with error (1). Closing log file.
```

**Comment by Gelmo** [comment]
Send Xorg.0.log as well, please

**Comment by Gelmo** [comment]
Looks like the dkms module was not built

**Comment by StripedMonkey** [comment]
Alright, so I fixed it. It took about till three in the morning to do but hey, now I know stuff. the steps I took based on my terminal history (I'm very fuzzy on the details of what goes on after 1 in the morning lol) are:
Of course grabbing the downgraded Xorg:
`pacaur -U https://archive.archlinux.org/packages/x/xf86-input-libinput/xf86-input-libinput-0.15.0-2-x86_64.pkg.tar.xz https://archive.archlinux.org/packages/x/xorg-server/xorg-server-1.18.3-3-x86_64.pkg.tar.xz`
Installing the AUR package for AMDGPU Pro:
`pacaur -S amdgpu-pro`
I'm not sure if this actually  was necisairy but I rebuilt the modules:
`sudo mkinitcpio -p linux`
Restarted and then nothing,I basically had 0 Xorg configuration so I decided to add that in:
I added the content from the https://wiki.archlinux.org/index.php/AMDGPU wiki page even though it was already using the AMDGPU drivers :man_shrugging: I added stuff verbatim to the wiki to the following: 
`/etc/mkinitcpio.conf`
`/etc/X11/xorg.conf.d/20-amdgpu.conf`
Even though I KNOW I didn't have the radeon drivers:
`/etc/modprobe.d/radeon.conf`
Remade the modules:
`mkinitcpio -p linux`
Nothing again, At this point someone suggested I just try to download the snapshot of the installer and try installing that:
`wget https://aur.archlinux.org/cgit/aur.git/snapshot/amdgpu-pro-installer.tar.gz`
`tar -xzvf amdgpu-pro-installer.tar.gz`
`makepkg -sci`
It failed. This leads me to believe that for whatever reason I didn't get all the required dependencies. The dependencies that I got were:
`lib32-libomxil-bellagio`
`lib32-ncurses5-compat-libs` <- This one failed because I was using pacaur and there is a thing where it refuses to build even if you --force it if the .SRCINFO and the PKGBUILD do not match. I ended up doing it with yaourt.
Repeat the AMDGPU pro snapshot steps
THEN I notice that I get some errors at the end of installing that complain about DKMS headers. I check for the `linux-headers` package in my system using pacaur (because habit) and get NOTHING. Knowing this can't be right I decide to do it with pacman and get the `linux-headers` package in core. Its not installed at least for my current kernel version.
Reboot and I get the beautiful LightDM login
:D

**Comment by brainpower** [comment]
Problem is, we can't directly depend on linux-headers, b/c users could have any kernel out of at least linux, linux-lts, linux-cik, any other kernel on AUR or even a completely selfmade kernel installed, and each has it's own headers package.
So nothing we could do here...
except advising to carefully read pacman output. 😄

**Comment by StripedMonkey** [comment]
Ya, Although the fact that when I downloaded the snapshot it installed
dependencies Vs. The AUR package which didn't indicates that there might be
a problem there

**Comment by Gelmo** [comment]
Do you get that with pacaur? If so, what happens when you get the aur package but use makepkg?

**Comment by StripedMonkey** [comment]
I'm not sure what you mean, I downloaded the snapshot and installed that
using makepkg which resulted in dependencies that were previously not
installed being installed. The time that it was not installed properly was
using pacaur although I do not know if that was even the issue as I also
apparently did not have the linux headers installed (which I find extremely
wierd) which might have been the problem in the first place.
