### ISSUE TITLE
Provide a version of libdrm that allows installation of mesa-git from AUR

### ISSUE THREAD

**Issue by Gelmo** [Ashark/archlinux-amdgpu#43]
```
configure: error: Package requirements (libdrm >= 2.4.75 libdrm_intel >= 2.4.75) were not met:

Requested 'libdrm >= 2.4.75' but version of libdrm is 2.4.70
No package 'libdrm_intel' found
```
I added "=2.4.75-1" the provides fields for libdrm and lib32-libdrm in gen-PKGBUILD.py and PKGBUILD, recompiled/installed, yet I'm still getting 2.4.70. I'm not sure if this is even possible to fix or not without waiting for new packages from AMD. Can anyone explain to me whether or not this is possible, and why?

**Comment by brainpower** [comment]
The Version "2.4.70" should come from the installed *.pc file for the amd-libdrm, look for it in /opt/amdgpu-pro/<libdir>/pkg-config/libdrm.pc .
Increasing the version there could work, but then building mesa-git will most likely fail at compile time if the API changed... 
So you'll probably have to wait for newer version from AMD anyway.

I may look into getting amd-libdrm and mesa libdrm to work nicely alongside each other, if I have some time to spare. (In a few weeks or months, maybe.)

**Comment by Ashark** [comment]
Currently, libdrm-amdgpu (generated from provided deb packages) can be installed alongside with normal libdrm.
