### ISSUE TITLE
libglvnd conflict (via mesa)

### ISSUE THREAD

**Issue by mikedilger** [Ashark/archlinux-amdgpu#50]
I'm getting a conflict with libglvnd (nvidia's vendor neutral thing).  In particular:
1) Lots of things depend on gtk3
2) gtk3 depends on mesa
3) mesa depends on libglvnd
4) amdgpu-pro-libgl conflicts with libglvnd

I installed ncurses5-compat-libs from AUR, and downgraded to these packages:
linux-4.9.11-1-x86_64.pkg.tar.xz
xf86-input-evdev-2.10.2-1-x86_64.pkg.tar.xz
xf86-input-keyboard-1.8.1-2-x86_64.pkg.tar.xz
xf86-input-libinput-0.20.0-1-x86_64.pkg.tar.xz
xorg-server-1.18.4-1-x86_64.pkg.tar.xz
xorg-server-1.18.4-1-x86_64.pkg.tar.xz.sig
xorg-server-common-1.18.4-1-x86_64.pkg.tar.xz
xorg-server-common-1.18.4-1-x86_64.pkg.tar.xz.sig
xorg-server-devel-1.18.4-1-x86_64.pkg.tar.xz
xorg-server-xvfb-1.18.4-1-x86_64.pkg.tar.xz
xorg-server-xwayland-1.18.4-1-x86_64.pkg.tar.xz

Maybe mesa needs a downgrade?

Also, is the lib32 part of this required, or can those packages be skipped?

I'm new to arch (as of this morning) so I'm possibly simply ignorant of the right way of doing things.  I'd appreciate any feedback.

**Comment by mikedilger** [comment]
Oh man, it appears a lot of stuff depends on this libglvnd (cairo, libva, mesa, sdl2, xorg-server, xorg-server-xephyr, xorg-server-xvfb, xorg-server-xwayland, xorg-xdriinfo)

**Comment by corngood** [comment]
Ugh, yeah, this looks like a mess.  `mesa-libgl` was previously it's own package, so things could use `mesa` for headers without installing the driver.

I think you'll need to install https://aur.archlinux.org/packages/mesa-noglvnd/ to satisfy the mesa requirements.

**Comment by mikedilger** [comment]
I didn't know about that package.  Thanks!

(Now I get a SEGV in Xorg.   https://gist.github.com/mikedilger/3ea2f4bce448d643552f1fcb91e87f61)

**Comment by corngood** [comment]
First of all, I see:

> AMDGPU(0): Failed to open amdgpu hybrid version

It means the amdgpu-pro dkms driver isn't loaded.  Make sure you are using a linux 4.8 or 4.9 kernel, and that you have the dkms package installed.

However, that shouldn't cause a crash.  A crash like that usually means it's loading the open source version of some shared library that's supposed to be provided by amdgpu-pro.  For example. could you try: `pacman -Qo /usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so`?

**Comment by mikedilger** [comment]
I'm quite sure I was using linux 4.9.11-1 and amdgpu-pro-dkms-17.10.401251-2, because these packages are in the directory that my script was using to downgrade/install everything.

I can't easily test anymore.  I swapped for my nvidia card because this was getting to hard.

If I get time I'll try the AMD card again (I need to test on AMD anyways), but I'm finally able to do vulkan game development again and I need to get a few things done while my workstation is working.

**Comment by corngood** [comment]
Have you considered just using the open source drivers?  The vulkan driver in mesa 17 is pretty good IMO, and it's so much less painful to install/update.

**Comment by mikedilger** [comment]
I didn't know the open source drivers had vulkan support, much less good support. I'll try that.

**Comment by kusayuzayushko** [comment]
ok, i got the same error.

```
error: failed to prepare transaction (conflicting dependencies)
:: amdgpu-pro-libgl and libglvnd are in conflict
```
I have mesa-noglvnd installed, but still
```
[kusayu@crypto-farm:~/archlinux-amdgpu]$ pacman -Q mesa-noglvnd
mesa-noglvnd 17.1.0-1
```
Is there any way to fox it?

**Comment by corngood** [comment]
You'll want to remove at least `libglvnd`, `mesa-libgl-noglvnd`, `mesa-vdpau-noglvnd`, `opencl-mesa-noglvnd`, `vulkan-radeon-noglvnd` when installing amdgpu-pro.

**Comment by kusayuzayushko** [comment]
That's was quick, thank you.
I've removed all of that, but still get the same error. Anything else i can remove?

**Comment by corngood** [comment]
Can you get any more info about the conflict, like the file name that's conflicting?

**Comment by corngood** [comment]
Actually never-mind, it's probably a declared `conflict=`

**Comment by corngood** [comment]
Is there actually a package `libglvnd`?  Or is `libglvnd` provided by some other package?  Maybe `pacman -Qo /usr/lib/libGL.so`?  I don't have access to an Arch system right now, so I'm working from memory.

**Comment by kusayuzayushko** [comment]
```
[kusayu@crypto-farm:~/archlinux-amdgpu]$ pacman -Qs gl
local/dbus-glib 0.108-1
    GLib bindings for DBUS
local/glib-networking 2.50.0-2
    Network extensions for GLib
local/glib2 2.52.2+9+g3245eba16-1
    Low level core library
local/glibc 2.25-4 (base)
    GNU C Library
local/glproto 1.4.17-1
    X11 OpenGL extension wire protocol
local/lib32-glibc 2.25-4
    GNU C Library (32-bit)
local/libepoxy 1.4.3-1
    Library handling OpenGL function pointer management
local/libmm-glib 1.6.8-1
    ModemManager library
local/libnm-glib 1.8.0-1
    NetworkManager client library (legacy)
local/mesa-noglvnd 17.1.0-1
    an open-source implementation of the OpenGL specification - non-libglvnd version
[kusayu@crypto-farm:~/archlinux-amdgpu]$ pacman -Qs glv
local/mesa-noglvnd 17.1.0-1
    an open-source implementation of the OpenGL specification - non-libglvnd version
[kusayu@crypto-farm:~/archlinux-amdgpu]$ pacman -Qo /usr/lib/libGL.so
error: failed to read file '/usr/lib/libGL.so': No such file or directory
[kusayu@crypto-farm:~/archlinux-amdgpu][1]$ pacman -Qs libglvnd
local/mesa-noglvnd 17.1.0-1
    an open-source implementation of the OpenGL specification - non-libglvnd version
```

find / -name 'libGL' gives me nothing.

**Comment by corngood** [comment]
Does it still say
```
error: failed to prepare transaction (conflicting dependencies)
:: amdgpu-pro-libgl and libglvnd are in conflict
```
?

That looks like a conflict with:
> https://www.archlinux.org/packages/extra/x86_64/libglvnd/

but you don't seem to have it installed.

**Comment by kusayuzayushko** [comment]
Yes, same error (even after reboot, just in case). And yes, i don't have it installed.

**Comment by kusayuzayushko** [comment]
Hm, that's looks strange to me. Inone hand, libglvnd is in 'conflict=' but in the other hand...
```
[kusayu@crypto-farm:~/archlinux-amdgpu]$ sudo pacman -U amdgpu-pro-17.10.401251-2-x86_64.pkg.tar.xz
...
resolving dependencies...
:: There are 3 providers available for libgl:
:: Repository extra
   1) libglvnd  2) nvidia-304xx-utils  3) nvidia-340xx-utils

Enter a number (default=1):
```

**Comment by brainpower** [comment]
libgl should be provided by one of the amdgpu-pro packages, amdgpu-pro-libgl or something like that.
If you add it to the pacman -U command, to install it *at the same time* as the main package, there shouldn't any dependency problems.

**Comment by Ashark** [comment]
amdgpu-pro-libgl now provides libgl, seems resolved.
