### ISSUE TITLE
17.50 was released

### ISSUE THREAD

**Issue by brainpower** [Ashark/archlinux-amdgpu#55]
Driver Download Site: https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx
Phoronix Article: https://www.phoronix.com/vr.php?view=25640

This release seems to contain open-source mesa components as well as the closed-source components.
It might take some time to figure out how to package this without breaking arch's mesa or "masking" the newer mesa stack with the older bundled one. It is said they bundle 17.2.4, while arch has 17.3 already, which has many improvements.

**Comment by znmeb** [comment]
They're just trolling us now. :-(

**Comment by Gelmo** [comment]
Quick question; what does 17.50/4.9 provide that isn't provided with 4.15/mesa from git/AMD DC? I understand PRO provides the proprietary libraries, but I would like to know the difference in user-available features, if possible.

**Comment by Gelmo** [comment]
Here's some relevent info.
https://www.phoronix.com/scan.php?page=news_item&px=17.50-RADV-RadeonSI-Features

**Comment by znmeb** [comment]
Sigh - I tried it on my Ubuntu 16.04.3 parition and it doesn't work, even in "headless" (OpenCL only) mode. They say it will work with 16.04.4. This is madness.

**Comment by svenstaro** [comment]
Did anyone make any progress on this?

**Comment by znmeb** [comment]
I have the `opencl-amd` package from 17.50 running on Arch on my AMD card. That piece has been ported and it works. As I noted above, the supposedly-supported Ubuntu 16.04 version does *not* work on the same machine.

**Comment by derdigge** [comment]
Hello all.

just stombled in here by googlń arround. Amdgpupro provides functionality for miners. 
I experience +30% when using theyre driver on ubuntu 16. So it would be nice if there will be a version bump :)

thanks.

**Comment by znmeb** [comment]
@derdigge Have you tried an OpenCL miner? I'm not into mining but I've seen them in the AUR.

**Comment by derdigge** [comment]
yes i did. and it crashed after about 3 hours :) 
So i wont recommend the 17.50

anyone got this version from here installed? It doesent like me.
https://pastebin.com/9jx1rq7Z
lots missing deps. no matte if i pull here from git or from aur.

**Comment by mirh** [comment]
Possible *progress*?
https://github.com/pgarrity18/archlinux-amdgpu
http://www.ps3ita.it/forum/drivers-video-per-accelerazione-3d-su-archlinux-t6117-40.html
