### ISSUE TITLE
[question] How can I tell if I'm running the amdgpu-pro drivers? 

### ISSUE THREAD

**Issue by codebling** [Ashark/archlinux-amdgpu#61]
I've searched online, read several forum posts, Q&A and relevant Arch wiki articles but I can't figure out how to check whether the amdgpu-pro drivers are being used. I've [posted on StackExchange](https://unix.stackexchange.com/q/546593/72873) as well, but got no response. How can I tell if the amdgpu-pro drivers are running? Why are DKMS and mkinitcpio not triggered when installing the pro drivers, aren't there kernel components to the pro drivers? 

I've checked output from `inxi -Gxxxx` and `lspci -k` but I can't find any "pro" reference.

**Comment by marwonline** [comment]
I'm currently trying out `amdgpu-pro` too and had the same question. IMHO nothing points to the user space driver directly. 
But when running `glxinfo | grep OpenGL` the open source driver & mesa showed OpenGL 4.5 only. 
With`amdgpu-pro` I  see OpenGL version `4.6.13572` for my RX 580.

**Comment by codebling** [comment]
@marwonline let me know if you find an answer. I solved all of my issues regarding color inversion and HDMI sound on the open-source driver, so I'm currently running that, but would still like to know the answer to this question

**Comment by Ashark** [comment]
> how to check whether the amdgpu-pro drivers are being used?

I have answered in StackExchange and also noted in ArchWiki the way I do it.
> Why are DKMS and mkinitcpio not triggered when installing the pro drivers, aren't there kernel components to the pro drivers?

There is a dkms package for ubuntu, but it is not ported to Arch Linux. I cannot answer this question for sure.

**Comment by codebling** [comment]
Stack answer copied here: 
```
glxinfo | grep "OpenGL vendor string" | cut -f2 -d":" | xargs
```

If it returns X.Org, then you are running open source driver. If it returns Advanced Micro Devices, Inc., then you are running proprietary driver.
